---
development:
  cloud_name: palamariuk
  api_key: '919942263615318'
  api_secret: ZNtO1D9-gafN8kizOvMC7BJiGiY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: palamariuk
  api_key: '919942263615318'
  api_secret: ZNtO1D9-gafN8kizOvMC7BJiGiY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: palamariuk
  api_key: '919942263615318'
  api_secret: ZNtO1D9-gafN8kizOvMC7BJiGiY
  enhance_image_tag: true
  static_file_support: false
